name: Build and Test Redbean on Test Branch

on:
  push:
    branches:
      - test-branch   # Replace this with the name of your test branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download redbean.com binary (or use your pre-included one)
      - name: Download redbean.com
        run: |
          curl -O https://redbean.dev/redbean.com
          chmod +x redbean.com

      # Zip the repository content into the redbean.com file
      - name: Add content to redbean.com
        run: |
          zip -r redbean.com ./*

      # (Optional) Save the zipped file as an artifact for inspection during testing
      - name: Upload redbean as artifact
        uses: actions/upload-artifact@v3
        with:
          name: redbean
          path: redbean.com
