name: Build and Test Redbean on Test Branch

on:
  push:
    branches:
      - test-branch   # Replace with your test branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download redbean.com binary
      - name: Download redbean.com
        run: |
          curl -f -O https://redbean.dev/redbean.com || exit 1
          chmod +x redbean.com || exit 1

      # Zip the repository content into the redbean.com file
      - name: Add content to redbean.com
        run: |
          zip -r redbean.com ./* || exit 1

      # (Optional) Upload the zipped file as an artifact
      - name: Upload redbean as artifact
        uses: actions/upload-artifact@v3
        with:
          name: redbean
          path: redbean.com
