name: Build and Test Redbean on Test Branch

on:
  push:
    branches:
      - test-branch   # Replace with your test branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download redbean.com binary
      - name: Download redbean.com
        run: |
          curl -O https://redbean.dev/redbean.com
          chmod +x redbean.com
          
      # Unzip redbean.com contents
      - name: Unzip redbean.com
        run: unzip redbean.com -d extracted_files

      # Copy repo files to extracted_files
      - name: Add repo files
        run: cp -r ./* extracted_files/
        
      # Repackage everything into redbean.com
      - name: Repackage redbean.com
        run: |
          cd extracted_files
          zip -r ../redbean.com ./*
          cd ..

      # (Optional) Upload the zipped file as an artifact
      - name: Upload redbean as artifact
        uses: actions/upload-artifact@v3
        with:
          name: aumono
          path: redbean.com
