name: Build and Package Redbean Application

on:
  push:
    branches:
      - test-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Download the latest redbean.com
      - name: Download Redbean
        run: wget https://redbean.dev/redbean-latest.com -O redbean.com

      # Create a ZIP archive of the repository files, excluding unnecessary files
      - name: Create ZIP Archive
        run: |
          zip -r site.zip . -x ".git/*" "redbean.com" "site.zip" ".github/*"

      # Append the ZIP archive to redbean.com
      - name: Append ZIP to Redbean
        run: cat site.zip >> redbean.com

      # Upload the redbean.com as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: redbean.com
          path: redbean.com #
