name: Build and Test Redbean on Test Branch

on:
  push:
    branches:
      - test-branch   # Replace with your test branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download redbean.com binary
      - name: Download redbean.com
        run: |
          curl -O https://redbean.dev/redbean.com
          chmod +x redbean.com
      
      # Download redbean.com binary          
      - name: Download redbean.com zip
        run: |
          curl -O https://cosmo.zip/pub/cosmos/bin/zip
          chmod +x zip

      - name: Add repo files to redbean.com zip
        run: |
          ./zip -r redbean.com ./art
          
      # (Optional) Upload the zipped file as an artifact
      # - name: Upload redbean as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: aumono
      #     path: redbean.com
