name: Build and Package Redbean Application

on:
  push:
    branches:
      - test-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Download the latest redbean.com
      - name: Download Redbean
        run: wget https://redbean.dev/redbean-latest.com -O redbean.com

      # Create ZIP Archive
      - name: Create ZIP Archive
        run: |
          zip -r site.zip . -x ".git/*" "redbean.com" "site.zip" ".github/*"

      # Append ZIP to Redbean
      - name: Append ZIP to Redbean
        run: cat site.zip >> redbean.com

      # Make redbean.com executable
      - name: Make Executable
        run: chmod +x redbean.com

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MONO_GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Update version as needed
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      # Upload redbean.com to Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MONO_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./redbean.com
          asset_name: redbean.com
          asset_content_type: application/octet-stream
