name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow from GitHub Actions UI

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Check out the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Sitemap Script
      run: python sitemap.py ./ # Run your script to generate sitemap.txt

    - name: Commit Sitemap
      run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add sitemap.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update sitemap" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.MONO_GITHUB_TOKEN }}  # GitHub token is provided by default for authentication
